### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by tefito** [Xaviju/inkscape-placeholder#4]
Hello World !

I will try this plugin but when i want to use any service, i have this error message 

> (CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

**The complete error message :**

```
Traceback (most recent call last):
  File "unsplash.py", line 66, in <module>
    placeholder.affect()
  File "C:\Program Files\Inkscape\share\extensions/inkex.py", line 283, in affect
    self.effect()
  File "unsplash.py", line 31, in effect
    image = self._get_image()
  File "unsplash.py", line 44, in _get_image
    response = urllib2.urlopen(url)
  File "C:\Program Files\Inkscape\lib\python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Inkscape\lib\python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Program Files\Inkscape\lib\python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Program Files\Inkscape\lib\python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files\Inkscape\lib\python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Program Files\Inkscape\lib\python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
```

**Comment by Xaviju** [comment]
Cannot reproduce the issue.
Looking around seems a pretty common problem regarding your python installation but since I am no python expert I cannot help you. 
Hopefully someone can point you in the right direction.

**Comment by Xaviju** [comment]
Seems to be a problem related to how your system manage certifications.  More info here: https://stackoverflow.com/a/34506491/2883148

**Comment by bameda** [comment]
Yes, it seems a problem with the verification of the certificate for the uspash url https://api.unsplash.com 

Maybe you could upgrade OpenSSL in your system (I am not a windows user, sorry)
```
pip install --upgrade pyopenssl
```
Or updating python to a new version (>2.7.9)
